# extract useful information from S1
# input: csv files from session 1/encoding session generated by Psychopy
# output: csv files in Step1
# date: 16.07.2025

# Load dplyr
library(dplyr)

# Define base path
path_A <- "L:/Common/Users/Qiaoyue/MEG_project/"
# path_A <- "C:/Users/raude/Desktop/IB_Memory_Ren/"

# Path to participant list
participants_file <- paste0(path_A, "Data/participants.csv")

# Read participant IDs
participants <- read.csv(participants_file, stringsAsFactors = FALSE)


# Loop through each participant
for (subID in participants$subID) {
  
  # New output directory
  output_dir <- paste0(path_A, "Results/bhv/", subID, "/Step1/")
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
  }
  
  # Path to participant's S1 behavioral data
  bhv_path <- paste0(path_A, "Data/", subID, "/bhv/S1/")
  
  # List CSV files in the participant's bhv/S1 directory
  file_list <- list.files(path = bhv_path, pattern = "\\.csv$", full.names = TRUE)
  
  for (file in file_list) {
    # Read the CSV file
    data <- read.csv(file, stringsAsFactors = FALSE)
    
    # Filter for main task trials
    filtered_data <- data[!is.na(data$Formal_trials.thisRepN), ]
    
    # Calculate ITI
    ITI <- filtered_data$Text_wait.stopped - filtered_data$Text_wait.started
    
    # Create new data frame
    result_data <- data.frame(
      subID = filtered_data$participant,
      age = filtered_data$age,
      gender = filtered_data$gender_female1_male2,
      handedness = filtered_data$handedness_left1_right2,
      Congruency = filtered_data$Congruency,
      Picture = filtered_data$Picture,
      ITI = ITI,
      choice = filtered_data$key_resp_choice.keys,
      choice_rt = filtered_data$key_resp_choice.rt,
      Arating = filtered_data$slider_rating
    )
    
    # Add Actual_Location
    result_data <- result_data %>%
      mutate(Actual_Location = case_when(
        Congruency == "congruent" & (choice == "left" | choice == "7") ~ "left",
        Congruency == "congruent" & (choice == "right" | choice == "8") ~ "right",
        Congruency == "incongruent" & (choice == "left" | choice == "7") ~ "right",
        Congruency == "incongruent" & (choice == "right" | choice == "8") ~ "left",
        TRUE ~ NA_character_
      ))
    
    # Check for duplicate pictures
    if (any(duplicated(result_data$Picture))) {
      message("Repeated pictures in participant ", subID)
    }
    
    # Output file name
    output_file <- file.path(output_dir, paste0("main_", subID, ".csv"))
    
    # Write CSV
    write.csv(result_data, output_file, row.names = FALSE)
  }
}
