# extract useful information from S3
# input: csv files from session 1/encoding session generated by Psychopy
# output: csv files in Step1
# date: 16.07.2025

# Load required library
library(dplyr)

# Define base path
path_A <- "L:/Common/Users/Qiaoyue/MEG_project/"
# path_A <- "C:/Users/raude/Desktop/IB_Memory_Ren/"

# Read participant list
participants_file <- paste0(path_A, "Data/participants.csv")
participants <- read.csv(participants_file, stringsAsFactors = FALSE)

# Loop through each participant
for (subID in participants$subID) {
  
  # Define input and output paths
  bhv_path <- paste0(path_A, "Data/", subID, "/bhv/S3/")  # S3 data
  output_dir <- paste0(path_A, "Results/bhv/", subID, "/Step1/")
  
  # Create output directory if it doesn't exist
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
  }
  
  # List CSV files for this participant
  file_list <- list.files(path = bhv_path, pattern = "\\.csv$", full.names = TRUE)
  
  for (file in file_list) {
    # Read raw data
    data <- read.csv(file, stringsAsFactors = FALSE)
      
    result_data<- data.frame(
      rating_foroldnew = data$slider_rating[2],
      rating_forleftright = data$slider_rating[3]
    )
    
    #print(result_data)
      
      # Save main task results
      write.csv(result_data,
                file = paste0(output_dir, "ratings_", basename(file)),
                row.names = FALSE)
    }
    
  }

