# extract useful information from S2
# input: csv files from session 1/encoding session generated by Psychopy
# output: csv files in Step1
# date: 16.07.2025

# Load required library
library(dplyr)

# Define base path
path_A <- "L:/Common/Users/Qiaoyue/MEG_project/"
# path_A <- "C:/Users/raude/Desktop/IB_Memory_Ren/"

# Read participant list
participants_file <- paste0(path_A, "Data/participants.csv")
participants <- read.csv(participants_file, stringsAsFactors = FALSE)

# Loop through each participant
for (subID in participants$subID) {
  
  # Define input and output paths
  bhv_path <- paste0(path_A, "Data/", subID, "/bhv/S2/")  # S2 data
  output_dir <- paste0(path_A, "Results/bhv/", subID, "/Step1/")
  
  # Create output directory if it doesn't exist
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
  }
  
  # List CSV files for this participant
  file_list <- list.files(path = bhv_path, pattern = "\\.csv$", full.names = TRUE)
  
  for (file in file_list) {
    # Read raw data
    data <- read.csv(file, stringsAsFactors = FALSE)
    
    # --- Process Main Task Data ---
    if (!is.null(data$Formal_trials.thisRepN)) {
      filtered_data <- data[!is.na(data$Formal_trials.thisRepN), ]
      
      ITI <- filtered_data$text_fix.stopped - filtered_data$text_fix.started
      
      result_data <- data.frame(
        subID = filtered_data$participant,
        Congruency = filtered_data$Congruency,
        Type = filtered_data$Type,
        Picture = filtered_data$Picture,
        ITI,
        rt = ifelse(filtered_data$keypress_memory.rt == "None", NA, as.numeric(filtered_data$keypress_memory.rt)),
        response_button = if ("chosen_answer" %in% colnames(filtered_data)) {
          filtered_data$chosen_answer
        } else {
          filtered_data$keypress_memory.keys
        }
      )
      
      # Add interpreted answer column
      result_data <- result_data %>%
        mutate(answer = case_when(
          response_button %in% c("num_4", "oldleft") ~ "oldleft",
          response_button %in% c("num_5", "oldright") ~ "oldright",
          response_button %in% c("num_1", "oldunknow") ~ "oldunknow",
          response_button %in% c("num_2", "new") ~ "new",
          TRUE ~ NA_character_
        ))
      
      # Check for duplicate pictures
      if (any(duplicated(result_data$Picture))) {
        warning(paste("Repeated pictures in", file))
      }
      
      # Save main task results
      write.csv(result_data,
                file = paste0(output_dir, "recognition_", basename(file)),
                row.names = FALSE)
    }
    
  }
}
